[package]
name = "kludgine"
version = "0.0.2"
authors = ["Jonathan Johnson <jon@khonsulabs.com>"]
edition = "2018"
description = "An asynchronous app and 2d game framework"
readme = "./README.md"
license = "MIT"
keywords = ["gamedev", "graphics", "gui", "wgpu"]
categories = [
    "gui",
    "graphics",
    "rendering::engine",
    "game-engines",
    "asynchronous"
]
repository = "https://github.com/khonsulabs/kludgine"

[package.metadata.docs.rs]
all-features = true

[features]
default = ["bundled-fonts", "ecs"]
# Enable all bundled fonts. All bundled fonts are licensed under the Apache License 2.0.
# For more information, see here: https://github.com/khonsulabs/kludgine/tree/master/fonts/README.md
bundled-fonts = ["bundled-fonts-roboto"]
bundled-fonts-roboto = ["bundled-fonts-enabled"]
# Internal feature that exports the bundled_fonts module
bundled-fonts-enabled = []
ecs = ["legion", "sorted-vec"]
serialization = ["serde", "euclid/serde", "palette/serializing"]

[dependencies]
easygpu = { version = "0.0.2" }
easygpu-lyon = { version = "0.0.2" }
lyon_tessellation = "0.16"
winit = "0.23"
image = "0.23"
crossbeam = "0.8"
lazy_static = "1"
thiserror = "1.0"
anyhow = "1.0"
rusttype = { version = "0.9", features = ["gpu_cache"] }
json = "0.12"
platforms = "1"
generational-arena = "0.2"
ttf-parser = "0.6"
once_cell = "1"
approx = "0.3"
palette = "0.5"
async-channel = "1"
async-rwlock = "1"
async-handle = "0.1"
async-lock = "2"
smol = "1"
smol-timeout = "0.6"
easy-parallel = "3"
async-trait = "0.1"
futures = { version = "0.3", features = ["thread-pool"] }
futures-timer = "3"
derivative = "2"
euclid = "0.22"
legion = { version = "0.3", optional = true }
sorted-vec = { version = "0.4", optional = true }
serde = { version = "1", optional = true, features = ["derive"] }
anymap = "0.12"

[dev-dependencies]
rand = "0.7"
futures-await-test = "0.3"

[[example]]
name = "text"
required-features = ["bundled-fonts-roboto"]

[[example]]
name = "ui"
required-features = ["bundled-fonts-roboto"]

[patch.crates-io]
easygpu = { path = "../easygpu" }
easygpu-lyon = { path = "../easygpu-lyon" }
