[workspace]
members = ["kludgine", "core", "app", "xtask"]

# [patch.crates-io] # must be commented out for CI to succeed
# easygpu = { path = "../easygpu" }
# easygpu-lyon = { path = "../easygpu-lyon" }
