[package]
name = "kludgine"
version = "0.0.2"
authors = ["Jonathan Johnson <jon@khonsulabs.com>"]
edition = "2018"
description = "An asynchronous app and 2d game framework"
readme = "./README.md"
license = "MIT OR Apache-2.0"
keywords = ["gamedev", "graphics", "gui", "wgpu"]
categories = [
    "gui",
    "graphics",
    "rendering::engine",
    "game-engines",
    "asynchronous",
]
repository = "https://github.com/khonsulabs/kludgine"

[package.metadata.docs.rs]
all-features = true

[features]
default = ["bundled-fonts", "ecs", "smol-rt", "clipboard", "multiwindow"]
multiwindow = []
tokio-rt = ["tokio"]
smol-rt = ["smol", "smol-timeout"]
clipboard = ["arboard"]
# Enable all bundled fonts. All bundled fonts are licensed under the Apache License 2.0.
# For more information, see here: https://github.com/khonsulabs/kludgine/tree/master/fonts/README.md
bundled-fonts = ["bundled-fonts-roboto"]
bundled-fonts-roboto = ["bundled-fonts-enabled"]
# Internal feature that exports the bundled_fonts module
bundled-fonts-enabled = []
ecs = ["legion", "sorted-vec"]
serialization = ["serde", "euclid/serde", "palette/serializing"]
instrumentation = ["tracing", "tracing-futures"]

[dependencies]
winit = "0.24"
crossbeam = "0.8"
easygpu = "0.0.9"
easygpu-lyon = "0.0.9"
lyon_tessellation = "0.16"
image = ">=0.23.12"
lazy_static = "1"
thiserror = "1.0"
anyhow = "1.0"
rusttype = { version = "0.9", features = ["gpu_cache"] }
json = "0.12"
platforms = "1"
generational-arena = "0.2"
ttf-parser = "0.6"
once_cell = "1"
approx = "0.4"
palette = "0.5"
async-channel = "1"
async-rwlock = "1"
async-handle = "0.1"
async-lock = "2"
easy-parallel = "3"
async-trait = "0.1"
futures = "0.3"
futures-timer = "3"
derivative = "2"
euclid = "0.22"
legion = { version = "0.3", optional = true }
sorted-vec = { version = "0.5", optional = true }
serde = { version = "1", optional = true, features = ["derive"] }
anymap = "0.12"
arboard = { version = "1.1", optional = true }
instant = "0.1.9"
bytemuck = { version = "1", features = ["derive"] }

tracing = { version = "0.1", optional = true }
tracing-futures = { version = "0.2", optional = true }

smol-timeout = { version = "0.6", optional = true }
smol = { version = "1", optional = true }
tokio = { version = "1.0", features = ["full"], optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
winit = { version = "0.24", default-features = false, features = ["web-sys"] }
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Window", "Element", "Document"] }
wasm-bindgen = "0.2.74" # needs to match wgpu's version

[dev-dependencies]
rand = "0.7"
futures-await-test = "0.3"

[[example]]
name = "text"
required-features = ["bundled-fonts-roboto"]

[[example]]
name = "ui"
required-features = ["bundled-fonts-roboto"]

# [patch.crates-io] # must be commented out for CI to succeed
# easygpu = { path = "../easygpu" }
# easygpu-lyon = { path = "../easygpu-lyon" }
