[package]
name = "kludgine"
version = "0.1.0"
authors = ["Jonathan Johnson <jon@nilobject.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin="0.23"
glium = "0.26"
futures = {version="0.3.4", features=["thread-pool"]}
async-trait = "0.1"
async-std = "*"
lazy_static = "*"
thiserror="*"