[package]
name = "kludgine"
version = "0.1.0"
authors = ["Jonathan Johnson <jon@nilobject.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

bundled-fonts = ["bundled-fonts-roboto"]
bundled-fonts-enabled = []
bundled-fonts-roboto = ["bundled-fonts-enabled"]

[dependencies]
rgx = {version = "0.8", features=["renderer"]}
winit = "*"
thiserror="*"
anyhow="*"
crossbeam="*"
image="*"
async-trait="*"
futures = {version="0.3", features=["thread-pool"]}
lazy_static="*"
async-std = "1"
chrono = "*"
educe="0.4"
rusttype= { version = "0.9", features=["gpu_cache"]}

[dev-dependencies]
rand="*"

[[example]]
name = "text"
required-features = ["bundled-fonts-roboto"]