name: Coverage

on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install x11 dependencies for Kludgine
        run: |
          sudo apt-get update -y -qq
          sudo add-apt-repository ppa:kisak/kisak-mesa -y
          sudo apt-get install -yqq \
            libxcb-render-util0-dev \
            libxcb-shape0-dev \
            libxcb-xfixes0-dev \
            mesa-vulkan-drivers

      - name: Run code coverage
        run: |
          cargo xtask generate-code-coverage-report --install-dependencies

      - name: Deploy Docs
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: coverage/
          git-config-name: kl-botsu
          git-config-email: botsu@khonsulabs.com
          target-folder: /coverage/
          clean: true
