name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: khonsulabs/build-rust:latest
      options: "--security-opt seccomp=unconfined"

    steps:
      - uses: actions/checkout@v1
      - name: Run clippy
        run: cargo clippy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.GAC_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.GAC_SECRET_KEY }}
          SCCACHE_BUCKET: khonsulabs-gac
      - name: Run tests on stable
        run: |
          apt-get update && apt-get install zip -y
          cargo install grcov
          cargo test --all-features
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.GAC_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.GAC_SECRET_KEY }}
          SCCACHE_BUCKET: khonsulabs-gac
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
